---
###############################################################################
# Assertions
###############################################################################
# Test assert logic in roles.
#
# Assertions MUST be tested in the converge step as it requires applying the
# role under test.
#
# Args:
#   test_name: str - Test base name.
#   test_role: str - FQCN role to test assertions for.
#   test_fail_message: str - message to display when test fails.

- name: '{{ test_name ~ " | check requirements" }}'
  ansible.builtin.assert:
    quiet: true
    that:
      - test_name | length > 0
      - test_role | length > 0
      - test_fail_message | length > 0
    fail_msg: |

      ✘ r_pufky.data.test.assertions requires:

      test_name: '{{ test_name }}'
      test_role: '{{ test_role }}'
      test_fail_message: '{{ test_fail_message }}'

- name: '{{ test_name }}'
  block:
    - name: '{{ test_name ~ " | test setup" }}'
      ansible.builtin.set_fact:
        test__failed: true

    - name: '{{ test_name ~ " 🛆 EXPECTED FAILURE 🛆" }}'
      ansible.builtin.include_role:
        name: '{{ test_role }}'

  rescue:
    - name: '{{ test_name ~ " PASS ✔" }}'
      ansible.builtin.set_fact:
        test__failed: false

    - name: '{{ test_name ~ " PASS ✔" }}'
      ansible.builtin.debug:
        msg: '✔ TEST CASE PASSED'

  always:
    - name: '{{ test_name ~ " | FAIL ✘" }}'
      when: test__failed
      ansible.builtin.fail:
        msg: |

          ✘ TEST CASE FAILED
          {{ test_fail_message }}
