---
###############################################################################
# sysctl
###############################################################################
# Test sysctl settings.
#
# Args:
#   test_name: str - Test base name.
#   test_option: str - sysctl option to test.
#   test_value: bool - sysctl expected option value.
#   test_diff: bool - Display file diff on failure? Default: False.

- name: '{{ test_name ~ " | check requirements" }}'
  ansible.builtin.assert:
    quiet: true
    that:
      - test_name | length > 0
      - test_option | length > 0
      - test_value | length > 0
    fail_msg: |

      ✘ r_pufky.data.test.copy requires:

      test_name: '{{ test_name }}'
      test_option: '{{ test_option }}'
      test_value: '{{ test_value }}'

- name: '{{ test_name ~ " | query" }}'
  ansible.builtin.command:
    argv:
      - '/sbin/sysctl'
      - '--values'
      - '{{ test_option }}'
  register: test__result
  changed_when: false

- name: '{{ test_name ~ " | assert" }}'
  ansible.builtin.assert:
    quiet: true
    that:
      - test__result.stdout == test_value
    fail_msg: |

      ✘ TEST CASE FAILED
      sysctl should report {{ test_option }}={{ test_value }}

      {{ test__result.stdout if test_diff | default(false) else "" }}
